import { createHash } from 'node:crypto'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { clipboard, ClipboardItem, nativeImage, type NativeImage } from 'electron'
import type { ClipItem, ClipPayload } from '@shared/types'

/**
 * Everything OpenPaste reads from and writes to the system clipboard.
 * Electron 44+ exposes an async, W3C-style clipboard: `read()` returns
 * ClipboardItems whose `types` are MIME types, and raw platform formats show
 * up as `electron application/osclipboard;format="…"`.
 */

const RAW = 'electron application/osclipboard'

/** Formats password managers and other apps use to say "don't record this". */
const CONCEALED_MARKERS = [
	'org.nspasteboard.ConcealedType',
	'org.nspasteboard.TransientType',
	'org.nspasteboard.AutoGeneratedType',
	'com.agilebits.onepassword',
	'de.petermaurer.TransientPasteboardType',
	'ExcludeClipboardContentFromMonitorProcessing',
	'Clipboard Viewer Ignore',
	'x-kde-passwordManagerHint'
]

const IMAGE_TYPES = [
	'image/png',
	'image/jpeg',
	'image/gif',
	'image/webp',
	'image/bmp',
	'image/tiff'
]

export interface ClipboardState {
	types: string[]
	items: Electron.ClipboardItem[]
}

export interface ClipboardSnapshot {
	text?: string
	html?: string
	rtf?: string
	files?: string[]
	image?: NativeImage
	imageHash?: string
	concealed: boolean
}

export function sha1(data: string | Buffer | Uint8Array): string {
	return createHash('sha1').update(data).digest('hex')
}

export async function readState(): Promise<ClipboardState> {
	const items = await clipboard.read()
	const types = [...new Set(items.flatMap((i) => i.types))]
	return { types, items }
}

async function getBlob(state: ClipboardState, type: string): Promise<Blob | null> {
	const item = state.items.find((i) => i.types.includes(type))
	if (!item) return null
	try {
		const value = await item.getType(type)
		return value instanceof Blob ? value : null
	} catch {
		return null
	}
}

export async function getText(state: ClipboardState, type: string): Promise<string | undefined> {
	const blob = await getBlob(state, type)
	return blob ? await blob.text() : undefined
}

export function imageType(state: ClipboardState): string | undefined {
	return IMAGE_TYPES.find((t) => state.types.includes(t))
}

export async function readImageBuffer(state: ClipboardState): Promise<Buffer | null> {
	const type = imageType(state)
	if (!type) return null
	const blob = await getBlob(state, type)
	return blob ? Buffer.from(await blob.arrayBuffer()) : null
}

/** True when the clipboard carries a marker asking clipboard managers to look away. */
export async function isConcealed(state: ClipboardState): Promise<boolean> {
	for (const type of state.types) {
		if (!type.startsWith(RAW)) continue
		if (CONCEALED_MARKERS.some((m) => type.includes(m))) return true
		// Windows: CanIncludeInClipboardHistory = 0 means "don't keep this in history".
		if (type.includes('CanIncludeInClipboardHistory')) {
			const blob = await getBlob(state, type)
			const bytes = blob ? new Uint8Array(await blob.arrayBuffer()) : null
			if (bytes && bytes.length >= 4 && bytes.every((b, i) => i >= 4 || b === 0)) return true
		}
	}
	return false
}

export function parseUriList(list: string | undefined): string[] {
	if (!list) return []
	const files: string[] = []
	for (const line of list.split(/\r?\n/)) {
		const value = line.trim()
		if (!value || value.startsWith('#') || !value.startsWith('file:')) continue
		try {
			files.push(fileURLToPath(value))
		} catch {
			/* skip malformed entries */
		}
	}
	return files
}

/**
 * Reads everything needed to record a copy. Image decoding is skipped when
 * images aren't wanted or text is present (Office apps put a picture of the
 * selection on the clipboard next to the text, which we don't want).
 */
export async function readSnapshot(
	state: ClipboardState,
	options: { captureImages: boolean; captureFiles: boolean; imageBuffer?: Buffer | null }
): Promise<ClipboardSnapshot> {
	const snapshot: ClipboardSnapshot = { concealed: await isConcealed(state) }
	if (snapshot.concealed) return snapshot

	// File copies: the standard uri-list, or GNOME Files' own format ("copy\nfile:///…").
	const fileTypes = state.types.filter(
		(t) => t === 'text/uri-list' || (t.startsWith(RAW) && t.includes('gnome-copied-files'))
	)
	for (const type of fileTypes) {
		const files = parseUriList(await getText(state, type))
		if (files.length) {
			if (options.captureFiles) snapshot.files = files
			return snapshot
		}
	}

	snapshot.text = await getText(state, 'text/plain')
	if (snapshot.text !== undefined && snapshot.text.trim() === '') snapshot.text = undefined
	if (snapshot.text !== undefined) {
		snapshot.html = await getText(state, 'text/html')
		snapshot.rtf = await getText(state, 'text/rtf')
		return snapshot
	}

	if (options.captureImages && imageType(state)) {
		const buffer = options.imageBuffer ?? (await readImageBuffer(state))
		if (buffer && buffer.length) {
			const image = nativeImage.createFromBuffer(buffer)
			if (!image.isEmpty()) {
				snapshot.image = image
				snapshot.imageHash = sha1(buffer)
			}
		}
	}
	return snapshot
}

/** Writes an item back to the clipboard, optionally as plain text only. */
export async function writeItem(
	item: ClipItem,
	payload: ClipPayload | null,
	options: { plain: boolean; imagePath?: string }
): Promise<void> {
	if (item.kind === 'image' && options.imagePath) {
		const png = nativeImage.createFromPath(options.imagePath).toPNG()
		await clipboard.write([
			new ClipboardItem({ 'image/png': new Blob([png], { type: 'image/png' }) })
		])
		return
	}

	if (item.kind === 'file' && item.files?.length) {
		const uris = item.files.map((f) => pathToFileURL(f).toString()).join('\r\n')
		const entry: Record<string, string> = { 'text/plain': item.files.join('\n') }
		if (!options.plain) entry['text/uri-list'] = uris
		await clipboard.write([new ClipboardItem(entry)])
		return
	}

	const text = payload?.text ?? item.preview
	if (options.plain || (!payload?.html && !payload?.rtf)) {
		await clipboard.writeText(text)
		return
	}
	const entry: Record<string, string> = { 'text/plain': text }
	if (payload.html) entry['text/html'] = payload.html
	if (payload.rtf) entry['text/rtf'] = payload.rtf
	await clipboard.write([new ClipboardItem(entry)])
}
